eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka/

spring:
  cloud:
    consul:
      enabled: false
